### ISSUE TITLE
Running an application in Quartz

### ISSUE THREAD

**Issue by vandana96** [HewlettPackard/quartz#1]
scripts/runenv.sh <your_app> 
This is the command mentioned to run our application. 
I am trying to run dhrystone-2.1 benchmark, but not sure how to run it on Quartz tool.
Please let me know how to run dhrystone-2.1 benchmark on Quartz tool.

**Comment by vandana96** [comment]
cmake .. command gives errors

Building C object bench/memlat/CMakeFiles/memlat.dir/memlat.c.o
/home/pesu/CCBD/new/quartz-master/bench/memlat/memlat.c: In function ‘safe_strtoull’:
/home/pesu/CCBD/new/quartz-master/bench/memlat/memlat.c:30:9: warning: implicit declaration of function ‘strtoull’ [-Wimplicit-function-declaration]
     r = strtoull(s, &ep, 10);
         ^
[ 84%] Linking C executable memlat
../../src/lib/libnvmemul.so: undefined reference to `hrtime_cycles'
../../src/lib/libnvmemul.so: undefined reference to `cycles_to_us'
collect2: error: ld returned 1 exit status
bench/memlat/CMakeFiles/memlat.dir/build.make:95: recipe for target 'bench/memlat/memlat' failed
make[2]: *** [bench/memlat/memlat] Error 1
CMakeFiles/Makefile2:297: recipe for target 'bench/memlat/CMakeFiles/memlat.dir/all' failed
make[1]: *** [bench/memlat/CMakeFiles/memlat.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Can you please let me know how I can fix this up?

**Comment by sarsanaee** [comment]
I got that error too @cherkaso @guimagalhaes while ```make clean all``` after ```cmake ..``` 
the operating system is Ubuntu 16.04 should go back to 14.04 or something else?!

**Comment by guimagalhaes** [comment]
A fix has been merged.
