### ISSUE TITLE
Setting read throttling register?

### ISSUE THREAD

**Issue by SudarsunKannan** [HewlettPackard/quartz#2]
Hello,

The BW throttling worked for me only after setting the THROTTLE_DDR_READ registers 
in the __set_read_bw function specifically for runs after the training phase when the bandwidth model file is already present.  Is this correct?

__set_read_bw() {
     ...
    node->cpu_model->set_throttle_register(regs, THROTTLE_DDR_ACT,         
                                                                         read_bw_model.throttle_reg_val[point]);
    //Added statement
    node->cpu_model->set_throttle_register(regs, THROTTLE_DDR_READ,         
                                                                         read_bw_model.throttle_reg_val[point]);
     ...
}

**Comment by hvolos** [comment]
That's interesting. When we tried setting the read/write throttling registers (i.e, THROTTLE_DDR_READ, THROTTLE_DDR_WRITE), those didn't have any effect. 

I think this might depend on the processor/chipset. What processor are using?
