### ISSUE TITLE
Will the write latency in NVM only mode or DRAM + NVM (Hybrid) mode be same as the write latency of the DRAM?

### ISSUE THREAD

**Issue by hkundnani** [HewlettPackard/quartz#31]
Since Quartz doesn't have write memory latency implemented yet as mentioned in Limitations of README file, does this mean that any write operations performed in NVM only mode or DRAM + NVM mode will have same write latency as that of the DRAM?

**Comment by hkundnani** [comment]
@hadibrais Thanks for pointing this out. Since I am not using `pflush`, can I assume that any writes done in NVM will have the same latency as DRAM since no additional latency has been added by quartz?

**Comment by hadibrais** [comment]
@hkundnani Yes.

**Comment by hkundnani** [comment]
@hadibrais Thank you. I will close this issue.
